package io.github.ns3154.mybatisassistant.dynamic;

/**
 * S5 编译器的稳定诊断类型，调用方不依赖异常文本。
 */
public enum MyBatisDynamicSqlDiagnosticCode {
    UNSUPPORTED_DYNAMIC_TAG,
    MISSING_REQUIRED_ATTRIBUTE,
    INVALID_CHOOSE_CHILD,
    DUPLICATE_OTHERWISE,
    MALFORMED_CDATA,
    UNKNOWN_XML_ENTITY,
    INVALID_BOOLEAN_ATTRIBUTE,
    INVALID_INCLUDE_REFID,
    INCLUDE_TARGET_NOT_UNIQUE,
    DUPLICATE_INCLUDE_PROPERTY,
    INVALID_INCLUDE_PROPERTY,
    UNRESOLVED_INCLUDE_PROPERTY,
    INCLUDE_PROPERTY_CYCLE,
    INCLUDE_CYCLE
}
