create table "USERS" (
    "ID" number generated by default as identity primary key,
    "NAME" varchar2(200 char) not null,
    "CREATED_AT" timestamp default systimestamp
);
select * from "USERS" order by "ID" offset 10 rows fetch next 20 rows only;
