package io.github.ns3154.mybatisassistant.database.jdbc;

import com.intellij.openapi.progress.EmptyProgressIndicator;
import com.intellij.openapi.progress.ProcessCanceledException;
import com.intellij.testFramework.fixtures.BasePlatformTestCase;
import io.github.ns3154.mybatisassistant.database.MyBatisDatabaseMetadataProvider;
import io.github.ns3154.mybatisassistant.database.MyBatisDatabaseRequest;
import io.github.ns3154.mybatisassistant.database.MyBatisDatabaseSnapshot;
import io.github.ns3154.mybatisassistant.database.MyBatisMetadataFreshness;
import io.github.ns3154.mybatisassistant.database.MyBatisSqlDialect;
import io.github.ns3154.mybatisassistant.generator.MyBatisGenerationConfiguration;
import io.github.ns3154.mybatisassistant.methodsql.MyBatisJoinRelationshipVerifier;
import io.github.ns3154.mybatisassistant.methodsql.MyBatisMethodSchema;

import java.sql.DriverManager;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public final class MyBatisJdbcMetadataProviderTest extends BasePlatformTestCase {
    private MyBatisJdbcDataSourceManager.SettingsState originalState;

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        originalState = manager().getState();
        manager().loadState(new MyBatisJdbcDataSourceManager.SettingsState());
    }

    @Override
    protected void tearDown() throws Exception {
        try {
            manager().loadState(originalState);
        } finally {
            super.tearDown();
        }
    }

    public void testCoreDescriptorRegistersCommunityProviderWithoutDatabaseToolsDependency() {
        List<MyBatisDatabaseMetadataProvider> providers = MyBatisDatabaseMetadataProvider
                .EP_NAME.getExtensionList().stream()
                .filter(provider -> "community-jdbc".equals(provider.id()))
                .toList();

        assertSize(1, providers);
        assertInstanceOf(providers.getFirst(), MyBatisJdbcMetadataProvider.class);
    }

    public void testLoadsRealH2MetadataWithKeysCommentsTypesAndStableOrdering() throws Exception {
        String id = "h2-" + UUID.randomUUID();
        String url = "jdbc:h2:mem:" + id + ";DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("create table PARENT ("
                    + "ID bigint generated by default as identity primary key, "
                    + "NAME varchar(80) not null, "
                    + "NAME_UPPER varchar generated always as (upper(NAME)))");
            statement.execute("comment on table PARENT is '父表'");
            statement.execute("comment on column PARENT.NAME is '名称'");
            statement.execute("create table CHILD (ID bigint primary key, "
                    + "PARENT_ID bigint, constraint FK_CHILD_PARENT "
                    + "foreign key (PARENT_ID) references PARENT(ID))");
            statement.execute("create view PARENT_VIEW as select ID, NAME from PARENT");
        }
        manager().replace(List.of(config(id, url, false)));

        MyBatisDatabaseSnapshot snapshot = new MyBatisJdbcMetadataProvider().load(
                getProject(),
                new MyBatisDatabaseRequest(Optional.of(id), Optional.of("PUBLIC")),
                new EmptyProgressIndicator()).getFirst();

        assertEquals(MyBatisSqlDialect.H2, snapshot.dialect());
        assertEquals(MyBatisMetadataFreshness.READY, snapshot.freshness());
        assertEquals(List.of("CHILD", "PARENT", "PARENT_VIEW"), snapshot.tables().stream()
                .map(table -> table.name())
                .toList());
        var child = snapshot.tables().getFirst();
        assertEquals(Optional.of("PUBLIC"), child.schema());
        assertEquals(List.of("ID", "PARENT_ID"), child.columns().stream()
                .map(column -> column.name())
                .toList());
        assertTrue(child.columns().getFirst().primaryKey());
        assertTrue(child.columns().get(1).foreignKey());
        var parent = snapshot.tables().get(1);
        var reference = child.columns().get(1).foreignKeyReference().orElseThrow();
        assertEquals(parent.catalog(), reference.catalog());
        assertEquals(parent.schema(), reference.schema());
        assertEquals("PARENT", reference.table());
        assertEquals("ID", reference.column());
        assertEquals(1, reference.columnCount());
        MyBatisGenerationConfiguration configuration = MyBatisGenerationConfiguration
                .standard("com.example");
        MyBatisMethodSchema childSchema = MyBatisMethodSchema.from(child, configuration);
        MyBatisMethodSchema parentSchema = MyBatisMethodSchema.from(parent, configuration);
        assertTrue(MyBatisJoinRelationshipVerifier.isVerifiedForeignKeyToPrimaryKey(
                childSchema,
                childSchema.fields().stream()
                        .filter(field -> field.columnName().equals("PARENT_ID"))
                        .findFirst()
                        .orElseThrow(),
                parentSchema,
                parentSchema.fields().stream()
                        .filter(field -> field.columnName().equals("ID"))
                        .findFirst()
                        .orElseThrow()));
        assertEquals(Optional.of("父表"), parent.comment());
        assertTrue(parent.columns().getFirst().autoIncrement());
        assertEquals(Optional.of("名称"), parent.columns().get(1).comment());
        assertFalse(parent.columns().get(1).nullable());
        assertTrue(parent.columns().get(2).generated());
        assertEquals(
                io.github.ns3154.mybatisassistant.database.MyBatisDatabaseObjectKind.VIEW,
                snapshot.tables().get(2).kind());
    }

    public void testMissingPasswordAndDisabledOrDifferentSourceStaySilent() {
        manager().replace(List.of(config("secret", "jdbc:h2:mem:secret", true)));
        MyBatisJdbcMetadataProvider provider = new MyBatisJdbcMetadataProvider();

        assertEmpty(provider.load(getProject(), MyBatisDatabaseRequest.all(),
                new EmptyProgressIndicator()));
        assertEmpty(provider.load(
                getProject(),
                new MyBatisDatabaseRequest(Optional.of("other"), Optional.empty()),
                new EmptyProgressIndicator()));

        MyBatisJdbcDataSourceConfig disabled = new MyBatisJdbcDataSourceConfig(
                "disabled", "Disabled", MyBatisSqlDialect.H2, "jdbc:h2:mem:disabled",
                "org.h2.Driver", List.of(), "sa", false,
                Optional.empty(), Optional.of("PUBLIC"), false);
        manager().replace(List.of(disabled));
        assertEmpty(provider.load(getProject(), MyBatisDatabaseRequest.all(),
                new EmptyProgressIndicator()));
    }

    public void testMarksCompositeForeignKeyColumnsFailClosed() throws Exception {
        String id = "h2-composite-" + UUID.randomUUID();
        String url = "jdbc:h2:mem:" + id + ";DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("create table TENANT_ROLE ("
                    + "TENANT_ID bigint not null, ROLE_ID bigint not null, "
                    + "primary key (TENANT_ID, ROLE_ID))");
            statement.execute("create table TENANT_USER ("
                    + "ID bigint primary key, TENANT_ID bigint not null, ROLE_ID bigint not null, "
                    + "constraint FK_TENANT_USER_ROLE foreign key (TENANT_ID, ROLE_ID) "
                    + "references TENANT_ROLE(TENANT_ID, ROLE_ID))");
        }
        manager().replace(List.of(config(id, url, false)));

        MyBatisDatabaseSnapshot snapshot = new MyBatisJdbcMetadataProvider().load(
                getProject(),
                new MyBatisDatabaseRequest(Optional.of(id), Optional.of("PUBLIC")),
                new EmptyProgressIndicator()).getFirst();
        var child = snapshot.tables().stream()
                .filter(table -> table.name().equals("TENANT_USER"))
                .findFirst()
                .orElseThrow();

        var tenantReference = child.columns().stream()
                .filter(column -> column.name().equals("TENANT_ID"))
                .findFirst()
                .orElseThrow()
                .foreignKeyReference()
                .orElseThrow();
        var roleReference = child.columns().stream()
                .filter(column -> column.name().equals("ROLE_ID"))
                .findFirst()
                .orElseThrow()
                .foreignKeyReference()
                .orElseThrow();
        assertEquals(2, tenantReference.columnCount());
        assertEquals(1, tenantReference.ordinal());
        assertEquals(2, roleReference.columnCount());
        assertEquals(2, roleReference.ordinal());
    }

    public void testCancellationAndDriverFailuresRemainTypedControlFlow() {
        manager().replace(List.of(config("cancel", "jdbc:h2:mem:cancel", false)));
        EmptyProgressIndicator cancelled = new EmptyProgressIndicator();
        cancelled.cancel();
        assertThrows(ProcessCanceledException.class, () -> new MyBatisJdbcMetadataProvider().load(
                getProject(), MyBatisDatabaseRequest.all(), cancelled));

        MyBatisJdbcDataSourceConfig broken = new MyBatisJdbcDataSourceConfig(
                "broken", "Broken", MyBatisSqlDialect.MYSQL, "jdbc:mysql://localhost/test",
                "missing.Driver", List.of(), "user", false,
                Optional.empty(), Optional.empty(), true);
        manager().replace(List.of(broken));
        IllegalStateException failure;
        try {
            new MyBatisJdbcMetadataProvider().load(
                    getProject(), MyBatisDatabaseRequest.all(), new EmptyProgressIndicator());
            throw new AssertionError("预期驱动加载失败");
        } catch (IllegalStateException expected) {
            failure = expected;
        }
        assertTrue(failure.getMessage().contains("Broken"));
        assertFalse(failure.getMessage().contains("jdbc:mysql"));
    }

    private MyBatisJdbcDataSourceManager manager() {
        return MyBatisJdbcDataSourceManager.getInstance(getProject());
    }

    private static MyBatisJdbcDataSourceConfig config(
            String id,
            String url,
            boolean passwordRequired) {
        return new MyBatisJdbcDataSourceConfig(
                id, id, MyBatisSqlDialect.H2, url, "org.h2.Driver", List.of(), "sa",
                passwordRequired, Optional.empty(), Optional.of("PUBLIC"), true);
    }
}
