package io.github.ns3154.mybatisassistant.sqltool.conversion;

import com.intellij.testFramework.fixtures.BasePlatformTestCase;
import io.github.ns3154.mybatisassistant.database.MyBatisSqlDialect;

import java.util.List;
import java.util.Optional;

public final class MyBatisJavaDdlGeneratorTest extends BasePlatformTestCase {
    public void testGeneratesMySqlDdlWithCompositeKeyCommentsAndIndex() {
        MyBatisJavaTableSchema table = new MyBatisJavaTableSchema(
                "order_item",
                Optional.of("shop"),
                Optional.of("订单明细"),
                List.of(
                        field("orderId", "order_id", "java.lang.Long",
                                false, true, false, true, "订单"),
                        field("itemId", "item_id", "java.lang.Long",
                                false, true, false, false, "商品"),
                        field("amount", "amount", "java.math.BigDecimal",
                                false, false, false, false, "金额")),
                List.of(new MyBatisJavaIndexSchema(
                        "idx_order_amount", List.of("order_id", "amount"), false)));

        MyBatisJavaDdlGeneration generation = MyBatisJavaDdlGenerator.generate(
                table, MyBatisSqlDialect.MYSQL);

        assertEquals("""
                CREATE TABLE `shop`.`order_item` (
                    `order_id` BIGINT NOT NULL COMMENT '订单',
                    `item_id` BIGINT NOT NULL COMMENT '商品',
                    `amount` DECIMAL(19, 2) NOT NULL COMMENT '金额',
                    PRIMARY KEY (`order_id`, `item_id`)
                ) COMMENT='订单明细';
                CREATE INDEX `idx_order_amount` ON `shop`.`order_item` (`order_id`, `amount`);
                """, generation.ddl());
        assertEmpty(generation.warnings());
        assertFalse(generation.confirmationRequired());
    }

    public void testGeneratesPostgresIdentityUuidAndCommentStatements() {
        MyBatisJavaTableSchema table = new MyBatisJavaTableSchema(
                "event",
                Optional.empty(),
                Optional.of("事件"),
                List.of(
                        field("id", "id", "java.lang.Long",
                                false, true, true, false, "主键"),
                        field("traceId", "trace_id", "java.util.UUID",
                                false, false, false, false, null),
                        field("at", "happened_at", "java.time.OffsetDateTime",
                                true, false, false, false, null)),
                List.of());

        String ddl = MyBatisJavaDdlGenerator.generate(
                table, MyBatisSqlDialect.POSTGRESQL).ddl();

        assertTrue(ddl.contains(
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"trace_id\" UUID NOT NULL"));
        assertTrue(ddl.contains("COMMENT ON TABLE \"event\" IS '事件';"));
        assertTrue(ddl.contains("COMMENT ON COLUMN \"event\".\"id\" IS '主键';"));
    }

    public void testGeneratesSqliteInlineAutoincrementPrimaryKey() {
        MyBatisJavaTableSchema table = new MyBatisJavaTableSchema(
                "sample", Optional.empty(), Optional.empty(),
                List.of(
                        field("id", "id", "long", false, true, true, false, null),
                        field("name", "name", "String", true, false, false, false, null)),
                List.of());

        String ddl = MyBatisJavaDdlGenerator.generate(
                table, MyBatisSqlDialect.SQLITE).ddl();

        assertTrue(ddl.contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"));
        assertFalse(ddl.contains("PRIMARY KEY ("));
    }

    public void testGeneratesDamengIdentityAndDoubleQuotedIdentifiers() {
        MyBatisJavaTableSchema table = new MyBatisJavaTableSchema(
                "user",
                Optional.of("SYSDBA"),
                Optional.empty(),
                List.of(field("id", "id", "long",
                        false, true, true, false, null)),
                List.of());

        String ddl = MyBatisJavaDdlGenerator.generate(
                table, MyBatisSqlDialect.DAMENG).ddl();

        assertTrue(ddl.contains("CREATE TABLE \"SYSDBA\".\"user\""));
        assertTrue(ddl.contains("\"id\" BIGINT IDENTITY(1,1) NOT NULL"));
    }

    public void testUnknownJavaTypeRequiresConfirmationAndSafeFallback() {
        MyBatisJavaTableSchema table = new MyBatisJavaTableSchema(
                "sample", Optional.empty(), Optional.empty(),
                List.of(field("metadata", "metadata", "com.example.Metadata",
                        true, false, false, false, null)),
                List.of());

        MyBatisJavaDdlGeneration generation = MyBatisJavaDdlGenerator.generate(
                table, MyBatisSqlDialect.GENERIC);

        assertTrue(generation.ddl().contains("\"metadata\" VARCHAR(255)"));
        assertEquals(1, generation.warnings().size());
        assertTrue(generation.confirmationRequired());
    }

    public void testRejectsDuplicateColumnsAndUnknownIndexColumn() {
        assertThrows(IllegalArgumentException.class, () -> MyBatisJavaDdlGenerator.generate(
                new MyBatisJavaTableSchema(
                        "sample", Optional.empty(), Optional.empty(),
                        List.of(
                                field("first", "value", "String",
                                        true, false, false, false, null),
                                field("second", "VALUE", "String",
                                        true, false, false, false, null)),
                        List.of()),
                MyBatisSqlDialect.MYSQL));
        assertThrows(IllegalArgumentException.class, () -> MyBatisJavaDdlGenerator.generate(
                new MyBatisJavaTableSchema(
                        "sample", Optional.empty(), Optional.empty(),
                        List.of(field("id", "id", "Long",
                                false, true, false, false, null)),
                        List.of(new MyBatisJavaIndexSchema(
                                "idx_missing", List.of("missing"), false))),
                MyBatisSqlDialect.MYSQL));
    }

    private static MyBatisJavaFieldSchema field(
            String property,
            String column,
            String type,
            boolean nullable,
            boolean primary,
            boolean autoIncrement,
            boolean inherited,
            String comment) {
        return new MyBatisJavaFieldSchema(
                property, column, type, nullable, primary, autoIncrement, inherited,
                Optional.ofNullable(comment));
    }
}
